#!/bin/bash

if [ "$REESEW_BUILD_TYPE" = "drafts" ]; then
    echo "Building with drafts included..."
    hugo --minify --buildDrafts --buildFuture
else
    echo "Building production version without drafts..."
    hugo --minify
fi
