baseURL = 'https://reesew.com/'
enableEmoji = true
enableRobotsTXT = true
languageCode = 'en-us'
title = 'Reese Williams'
theme = 'blog-theme'
[params]
  siteDescription = 'The homepage of Reese Williams: essays, travel, and general skullduggery.'

[taxonomies]
  tag = "tags"

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Essays"
    url = "/tags/essay/"
    weight = 2
[[menu.main]]
    name = "Reviews"
    url = "/tags/review/"
    weight = 3
[[menu.main]]
    name = "Travel"
    url = "/tags/travelogue/"
    weight = 4

[markup.goldmark.renderer]
unsafe= true
