baseURL = 'https://reesew.com/'
enableEmoji = true
enableRobotsTXT = true
languageCode = 'en-us'
title = 'Reese Williams'
theme = 'blog-theme'
[params]
  siteDescription = 'The homepage of Reese Williams: travel, books, photography, and lots of side quests.'
  xLink = 'https://x.com/_reesew'

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Thoughts"
    url = "/thoughts/"
    weight = 2
# TODO Unhide this when there are travelogues
#[[menu.main]]
#    name = "Travel"
#    url = "/travelogues/"
#    weight = 3
