baseURL = 'https://reesew.com/'
enableEmoji = true
enableRobotsTXT = true
languageCode = 'en-us'
title = 'Reese Williams'
theme = 'blog-theme'
[params]
  siteDescription = 'The homepage of Reese Williams: travel, books, and lots of side quests.'

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Writing"
    url = "/thoughts/"
    weight = 2
[[menu.main]]
    name = "Reading"
    url = "/book-reviews/"
    weight = 3
[[menu.main]]
    name = "Travel"
    url = "/travelogues/"
    weight = 4

[markup.goldmark.renderer]
unsafe= true
