[build.environment]
    HUGO_VERSION = "0.134.2"

[build]
  publish = "public/"
  command = "hugo"

  # The Lighthouse deploy check uses these headers to check for SEO,
  # so we should include them for an accurate Lighthouse score
  [context.staging]
    command = "hugo && cp ./_headers ./public/_headers"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
